const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const copy={
  uk:{back:'← На головну',consult:'Консультація',eyebrow:'/ КАТАЛОГ ОБЛАДНАННЯ',title:'Обладнання.<br><em>З актуальними цінами.</em>',lead:'Інвертори, акумулятори та компоненти, які ми використовуємо у реальних системах. Сумісність і комплектацію перевірить інженер.',listTitle:'Усі товари',searchLabel:'Пошук за брендом або моделлю',searchPlaceholder:'Наприклад: Deye 8 kW',all:'Усі',loading:'Завантажуємо каталог…',empty:'За вашим запитом нічого не знайдено.',models:n=>`${n} ${n===1?'модель':'моделей'}`,details:'Детальніше ↗',productEyebrow:'КАТАЛОГ ОБЛАДНАННЯ',zoomHint:'Натисніть на фото, щоб збільшити',power:'Потужність',grid:'Фази / напруга',price:'Ціна',name:"Ім'я *",phone:'Телефон *',send:'Надіслати запит ↗',more:'Додати більше інформації',note:'Нотатка',city:'Місто',contacts:'Контакти',onRequest:'За запитом',sending:'Надсилаємо…',sent:'Запит прийнято. Інженер зв’яжеться з вами найближчим часом.',failed:'Не вдалося надіслати. Перевірте ім’я та телефон.',close:'Закрити',enlarge:'Збільшити фото товару'},
  en:{back:'← Home',consult:'Consultation',eyebrow:'/ EQUIPMENT CATALOGUE',title:'Equipment.<br><em>With current prices.</em>',lead:'Inverters, batteries and components used in real engineered systems. An engineer will verify compatibility and configuration.',listTitle:'All products',searchLabel:'Search by brand or model',searchPlaceholder:'For example: Deye 8 kW',all:'All',loading:'Loading catalogue…',empty:'No products match your search.',models:n=>`${n} ${n===1?'model':'models'}`,details:'Details ↗',productEyebrow:'EQUIPMENT CATALOGUE',zoomHint:'Click the photo to enlarge',power:'Power',grid:'Phases / voltage',price:'Price',name:'Name *',phone:'Phone *',send:'Send enquiry ↗',more:'Add more information',note:'Note',city:'City',contacts:'Contacts',onRequest:'On request',sending:'Sending…',sent:'Enquiry received. An engineer will contact you shortly.',failed:'Could not send. Check your name and phone number.',close:'Close',enlarge:'Enlarge product photo'}
};
let lang=new URLSearchParams(location.search).get('lang')==='en'?'en':'uk';
let products=[];let filtered=[];let activeBrand='all';let activeProduct=null;
const grid=$('#catalog-grid');const status=$('#catalog-status');const count=$('#catalog-count');const search=$('#catalog-search');const filters=$('#catalog-filters');const dialog=$('#catalog-product-dialog');const lightbox=$('#catalog-image-lightbox');
function t(key,...args){const value=copy[lang][key];return typeof value==='function'?value(...args):value}
function applyLanguage(){document.documentElement.lang=lang;document.title=lang==='en'?'Inverters, batteries and energy equipment catalogue | INK':'Каталог інверторів, акумуляторів та обладнання | ІНК';$$('[data-copy]').forEach(node=>{const value=t(node.dataset.copy);if(value!==undefined)node.innerHTML=value});search.placeholder=t('searchPlaceholder');$$('[data-lang]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.lang===lang)));$('.catalog-theme').title=lang==='en'?'Change theme':'Змінити тему';$('.catalog-theme').setAttribute('aria-label',$('.catalog-theme').title);$('.catalog-dialog-close').setAttribute('aria-label',t('close'));$('.catalog-image-lightbox button').setAttribute('aria-label',t('close'));render()}
function productImage(item){return item.thumbnail||(Array.isArray(item.images)?item.images[0]:'')||''}
function translatedPhase(value=''){return lang==='en'?String(value).replace(/3 фази/gi,'3 phases').replace(/1 фаза/gi,'1 phase').replace(/До 12 модулів/gi,'Up to 12 modules'):value}
function render(){if(!grid)return;const query=search.value.trim().toLocaleLowerCase();filtered=products.filter(item=>{const brand=String(item.brand||'').toLocaleLowerCase();const haystack=[item.brand,item.model,item.power,item.phase,item.voltage].filter(Boolean).join(' ').toLocaleLowerCase();return(activeBrand==='all'||brand===activeBrand)&&(!query||haystack.includes(query))});count.textContent=t('models',filtered.length);grid.innerHTML=filtered.length?filtered.map(item=>{const image=productImage(item);return `<button class="catalog-card" type="button" data-id="${escapeHtml(item._id||'')}" aria-label="${escapeHtml((lang==='en'?'Open ':'Відкрити ')+`${item.brand||''} ${item.model||''}`)}"><span class="catalog-card-media">${image?`<img src="${escapeHtml(image)}" alt="${escapeHtml(`${item.brand||''} ${item.model||''}`)}" loading="lazy">`:'⚡'}</span><span class="catalog-card-copy"><span class="catalog-card-brand">${escapeHtml(item.brand||'ІНК')}</span><h3>${escapeHtml(item.model||'')}</h3><span class="catalog-card-specs">${escapeHtml([item.power,translatedPhase(item.phase),item.voltage].filter(Boolean).join(' · '))}</span><span class="catalog-card-bottom"><strong class="catalog-card-price">${escapeHtml(item.price||t('onRequest'))}</strong><span class="catalog-card-detail">${escapeHtml(t('details'))}</span></span></span></button>`}).join(''):`<div class="catalog-status"><b>${escapeHtml(t('empty'))}</b></div>`}
function buildFilters(){const brands=[...new Set(products.map(item=>String(item.brand||'').trim()).filter(Boolean))].sort();filters.innerHTML=`<button class="is-active" type="button" data-brand="all" aria-pressed="true">${escapeHtml(t('all'))}</button>${brands.map(brand=>`<button type="button" data-brand="${escapeHtml(brand.toLocaleLowerCase())}" aria-pressed="false">${escapeHtml(brand)}</button>`).join('')}`}
function markdown(value=''){const safe=escapeHtml(value).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');const lines=safe.split(/\r?\n/);let html='';let list=false;for(const line of lines){if(/^###?\s+/.test(line)){if(list){html+='</ul>';list=false}html+=`<h3>${line.replace(/^###?\s+/,'')}</h3>`}else if(/^[-•]\s+/.test(line)){if(!list){html+='<ul>';list=true}html+=`<li>${line.replace(/^[-•]\s+/,'')}</li>`}else if(line.trim()){if(list){html+='</ul>';list=false}html+=`<p>${line}</p>`}}if(list)html+='</ul>';return html}
async function openProduct(summary){let item=summary;if(!item.description){const response=await fetch(`/api/equipment/${encodeURIComponent(item._id)}`).catch(()=>null);if(response?.ok)item={...item,...await response.json()}}activeProduct=item;const images=(Array.isArray(item.images)&&item.images.length?item.images:[item.thumbnail]).filter(Boolean);const main=$('.catalog-product-media>img',dialog);main.src=images[0]||'';main.alt=`${item.brand||''} ${item.model||''}`.trim();main.setAttribute('aria-label',t('enlarge'));main.title=t('zoomHint');$('.catalog-product-gallery',dialog).innerHTML=images.length>1?images.map((src,index)=>`<button type="button" class="${index===0?'is-active':''}" data-image="${escapeHtml(src)}"><img src="${escapeHtml(src)}" alt=""></button>`).join(''):'';$('#catalog-product-title').textContent=`${item.brand||''} ${item.model||''}`.trim();$('.catalog-description').innerHTML=markdown(item.description||'');$('[data-field="power"]',dialog).textContent=item.power||'—';$('[data-field="grid"]',dialog).textContent=[translatedPhase(item.phase),item.voltage].filter(Boolean).join(' · ')||'—';$('[data-field="price"]',dialog).textContent=item.price||t('onRequest');const form=$('.catalog-enquiry-form',dialog);form.reset();$('.catalog-extra',dialog).hidden=true;$('.catalog-more',dialog).setAttribute('aria-expanded','false');$('.catalog-form-status',dialog).textContent='';dialog.showModal();$('.catalog-product-copy',dialog).scrollTop=0}
function openLightbox(){const source=$('.catalog-product-media>img',dialog);const target=$('img',lightbox);if(!source.src)return;target.src=source.src;target.alt=source.alt;lightbox.showModal()}
async function load(){status.hidden=false;grid.innerHTML='';const response=await fetch('/api/equipment').catch(()=>null);products=response?.ok?await response.json():[];status.hidden=true;buildFilters();applyLanguage()}
grid.addEventListener('click',event=>{const card=event.target.closest('.catalog-card');if(!card)return;const item=products.find(product=>String(product._id)===card.dataset.id);if(item)openProduct(item)});
filters.addEventListener('click',event=>{const button=event.target.closest('button[data-brand]');if(!button)return;activeBrand=button.dataset.brand;$$('button',filters).forEach(item=>{const selected=item===button;item.classList.toggle('is-active',selected);item.setAttribute('aria-pressed',String(selected))});render()});
search.addEventListener('input',render);$$('[data-lang]').forEach(button=>button.addEventListener('click',()=>{lang=button.dataset.lang;const url=new URL(location.href);if(lang==='en')url.searchParams.set('lang','en');else url.searchParams.delete('lang');history.replaceState({},'',url);applyLanguage()}));
$('.catalog-theme').addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=next;localStorage.setItem('ink-theme',next)});document.documentElement.dataset.theme=localStorage.getItem('ink-theme')||'dark';
$('.catalog-dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});$('.catalog-product-media>img',dialog).addEventListener('click',openLightbox);$('.catalog-product-media>img',dialog).addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openLightbox()}});$('.catalog-product-gallery',dialog).addEventListener('click',event=>{const button=event.target.closest('button[data-image]');if(!button)return;$('.catalog-product-media>img',dialog).src=button.dataset.image;$$('button',$('.catalog-product-gallery',dialog)).forEach(item=>item.classList.toggle('is-active',item===button))});$('.catalog-image-lightbox button').addEventListener('click',()=>lightbox.close());lightbox.addEventListener('click',event=>{if(event.target===lightbox)lightbox.close()});
$('.catalog-more').addEventListener('click',event=>{const expanded=event.currentTarget.getAttribute('aria-expanded')==='true';event.currentTarget.setAttribute('aria-expanded',String(!expanded));$('.catalog-extra',dialog).hidden=expanded});
$('.catalog-enquiry-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity()||!activeProduct)return;const fields=Object.fromEntries(new FormData(form).entries());const model=`${activeProduct.brand||''} ${activeProduct.model||''}`.trim();const submit=$('button[type="submit"]',form);const formStatus=$('.catalog-form-status',form);submit.disabled=true;formStatus.textContent=t('sending');const response=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:fields.name,phone:fields.phone,email:fields.email||'',city:fields.city||'',object:'Обладнання',need:`Запит по моделі: ${model}`,comment:[`Запит із каталогу: ${model}.`,fields.note||''].filter(Boolean).join(' '),website:fields.website||''})}).catch(()=>null);submit.disabled=false;formStatus.textContent=response?.ok?t('sent'):t('failed')});
applyLanguage();load();
